# Plugin version 1.7.5

send_msg_yourself: false
# This item is needed to be able to send a message to yourself
# Accepts only values 'true' and 'false'

default_sound: 'false'
# By default, the sound is turned off 'false', but you can change it
# It is necessary to indicate the name of the sound in uppercase and with underscores
# Example - msgsound: 'entity.player.levelup'
# All sounds you can find here - https://minecraft.fandom.com/wiki/Sounds.json/Bedrock_Edition_values
# Unfortunately not all of these sounds can be reproduced correctly
# Therefore, if the sound doesn't work and gives an error, then you should change the sound

default_volume: 50
# By default, the volume of notification sounds is set to '50', but it can be changed
# The volume value must be specified in the range from '0' to '100'

privatechat_start_char: '?'
# Start character for sending messages to private chat

confirm_sending: true
# Confirmation of sending an offline message

messages:
  incorrect_command: '<color:#ffff55>The command is specified incorrectly</color>'
  invalid_player: '<color:#ffff55>Invalid player value</color>'

  reloadmsg:
    reload_successfully: '<color:#55ffff>The plugin was successfully reloaded</color>'

  propertiesmsg:
    unknown_property: '<color:#ffff55>Unknown property</color>'
    usage: '<color:#ffff55>Usage: /propmsg <property> <value></color>'
    confirm_sending:
      usage: '<color:#ffff55>Usage: /msgprop confirm_sending <on | off></color>'
      property_set: '<color:#55ffff>Property</color> <b><color:#ffff55><property></color></b> <color:#55ffff>is set to</color> <b><color:#ffff55><value></color></b>'

  playermsg:
    usage: "<color:#ffff55><hover:show_text:'Click to send a message'><click:suggest_command:'/msg '>Usage: /msg <player> <message></click></hover></color>"
    not_send_offline_from_console: '<color:#ffff55>You cannot send messages to offline players from the console</color>'
    not_send_youself: '<color:#ffff55>You cannot send message yourself</color>'
    sender_pattern: '<b><color:#55ffff>[</color></b><color:#ffff55><sender></color> <b><color:#55ffff>-></color></b> <color:#ffff55><receiver></color><b><color:#55ffff>]</color></b> <color:#ffff55><message></color>'
    receiver_pattern: '<b><color:#55ffff>[</color></b><color:#ffff55><sender></color> <b><color:#55ffff>-></color></b> <color:#ffff55><receiver></color><b><color:#55ffff>]</color></b> <color:#ffff55><message></color>'
    click_send_reply: 'Click to send reply message'
    player_missing: '<color:#ffff55>This player is not on the server</color>'
    send_offline: '<color:#ffff55>Send this player an offline message?</color>'
    accept_send: '<color:#ffff55>Accept</color> <b><color:#55ffff>[✔]</color></b>'
    click_send_offline: 'Click to send offline message'

  replymsg:
    no_last_recipient: '<color:#ffff55>You do not have the latest recipient</color>'

  acceptsend:
    send_offline_successfully: '<color:#55ffff>You have successfully sent an offline message</color>'

  mailmsg:
    offline_pattern: '<b><color:#55ffff>[</color></b><color:#ffff55><sender></color> <b><color:#55ffff>-></color></b> <color:#ffff55><receiver></color><b><color:#55ffff>]</color></b> <color:#ffff55><message></color>'
    have_unread: "<color:#55ffff><hover:show_text:'Click to read messages'><click:run_command:'/mail'>You have unread messages (/mail - to read)</click></hover></color>"
    your_unread: '<color:#55ffff>Your unread messages:</color>'
    no_unread: '<color:#55ffff>You have no unread messages</color>'

  notificationmsg:
    usage: '<color:#ffff55>Usage: /notify <sound> <volume></color>'
    sound_missing: '<color:#ffff55>Invalid sound value</color>'
    successfully_changed: '<color:#55ffff>The notification sound has been successfully changed</color>'

  privatechat:
    message_template: '<b><color:#55ffff>[</color></b><color:#ffff55><group></color><b><color:#55ffff>]</color></b> <color:#ffff55><player></color><b><color:#55ffff>:</color></b> <message>'
    you_not_owner: '<color:#ffff55>You are not the owner of the private chat</color>'
    you_not_in_private_chat: '<color:#ffff55>You are not in a private chat</color>'
    you_already_in_private_chat: '<color:#ffff55>You are already in a private chat</color>'
    you_can_not_invite_yourself: '<color:#ffff55>You can not invite yourself</color>'
    you_can_not_kick_yourself: '<color:#ffff55>You can not kick yourself out</color>'
    create_successfully: '<color:#55ffff>Private chat</color> <b><color:#ffff55><group></color></b> <color:#55ffff>was successfully created</color>'
    chat_info: 'Show chat information'
    delete_successfully: '<color:#55ffff>Private chat</color> <b><color:#ffff55><group></color></b> <color:#55ffff>was deleted</color>'
    info:
      template: '<b><color:#55ffff>⏴-----</color><color:#ffff55><group></color><color:#55ffff>-----⏵</color></b>
                <br><color:#aaaaaa>Members:</color> <count_members> <color:#aaaaaa>owned by</color> <owner>
                <br><color:#ff5555><leave_text></color>   <color:#55ff55><invite_text></color>
                <br><b><color:#55ffff>⏴---------------⏵</color></b>'
      leave_text: '← Leave'
      leave_hover_text: 'Leave private chat'
      invite_text: '✉ Invite'
      invite_hover_text: 'Invite a player'
    leave_successfully: '<color:#55ffff>You have successfully left the</color> <b><color:#ffff55><group></color></b> <color:#55ffff>group</color>'
    leave_notification: '<b><color:#ffff55><player></color></b> <color:#55ffff>left the private chat</color>'
    kick_successfully: '<color:#55ffff>You have successfully kicked out</color> <b><color:#ffff55><player></color></b>'
    kick_notification: '<color:#55ffff>You have been kicked from</color> <b><color:#ffff55><group></color></b> <color:#55ffff>private chat</color>'
    kick_failed: '<color:#55ffff>Failed to kick out</color> <b><color:#ffff55><player></color></b>'
    invite_successfully: '<color:#55ffff>Invitation to</color> <b><color:#ffff55><player></color></b> <color:#55ffff>successfully sent</color>'
    invite:
      template: '<b><color:#ffff55><player></color></b> <color:#55ffff>invited you to a private chat</color> <b><color:#ffff55><group></color></b>
                <br><color:#55ff55><accept_text></color>'
      accept_text: '→ Join to private chat'
      accept_hover_text: 'Accept invitation'
    join_successfully: '<color:#55ffff>You have successfully joined the</color> <b><color:#ffff55><group></color></b> <color:#55ffff>private chat</color>'
    join_notification: '<b><color:#ffff55><player></color></b> <color:#55ffff>joined the private chat</color>'
    join_failed: '<color:#ffff55>Failed to join private chat</color>'
    usage:
      default: '<color:#ffff55>Usage: /privatechat <action> <arg>(if required)</color>'
      create: '<color:#ffff55>Usage: /privatechat create <group name></color>'
      delete: '<color:#ffff55>Usage: /privatechat delete</color>'
      info: '<color:#ffff55>Usage: /privatechat info</color>'
      leave: '<color:#ffff55>Usage: /privatechat leave</color>'
      kick: '<color:#ffff55>Usage: /privatechat kick <player></color>'
      invite: '<color:#ffff55>Usage: /privatechat invite <player></color>'
      join: '<color:#ffff55>Usage: /privatechat join <group ID></color>'

  blacklist:
    usage: "<color:#ffff55><hover:show_text:'Click to manage blacklist'><click:suggest_command:'/blacklist '>Usage: /blacklist <action> <args></click></hover></color>"
    yourself: '<color:#ffff55>You cannot add yourself to the blacklist</color>'
    already_block: '<color:#ffff55>This player is already blocked</color>'
    not_block: '<color:#ffff55>This player is not on the blacklist</color>'
    success_block: '<color:#55ffff>The player was successfully blocked</color>'
    success_unblock: '<color:#55ffff>The player has been successfully unblocked</color>'
    empty: '<color:#ffff55>Your blacklist is empty</color>'
    players: '<color:#55ffff>Players from your blacklist:</color> <color:#ffff55><blacklist></color>'
    you_cannot_send: '<color:#ffff55>You cannot send messages to this player</color>'
    you_have_blocked: '<color:#ffff55>You have blocked this player</color>'

  help_message: '<b><color:#55ffff>⏴-------</color><color:#ffff55>SimpleMsgPlugin</color><color:#55ffff>-------⏵</color></b>
  
  <color:#55ffff>Command:</color> <color:#ffff55>msghelp</color>
  
  <color:#55ffff>Description:</color> <color:#ffff55>This command allows you to display all possible plugin commands</color>
  
  <color:#55ffff>Usage:</color> <color:#ffff55>/<command></color>
  
  
  <color:#55ffff>Command:</color> <color:#ffff55>msgrc</color>
  
  <color:#55ffff>Description:</color> <color:#ffff55>This command allows you to reload the plugin config</color>
  
  <color:#55ffff>Usage:</color> <color:#ffff55>/<command></color>
  
  
  <color:#55ffff>Command:</color> <color:#ffff55>msg</color>
  
  <color:#55ffff>Description:</color> <color:#ffff55>This command allows you to send private messages to the player</color>
  
  <color:#55ffff>Usage:</color> <color:#ffff55>/<command> <player> <message></color>
  
  
  <color:#55ffff>Command:</color> <color:#ffff55>reply</color>
  
  <color:#55ffff>Description:</color> <color:#ffff55>This command allows you to send a private message to the last player who wrote to you</color>
  
  <color:#55ffff>Usage:</color> <color:#ffff55>/<command> <message></color>
  
  
  <color:#55ffff>Command:</color> <color:#ffff55>acceptsend</color>
  
  <color:#55ffff>Description:</color> <color:#ffff55>This command allows you to accept sending an offline message</color>
  
  <color:#55ffff>Usage:</color> <color:#ffff55>/<command></color>
  
  
  <color:#55ffff>Command:</color> <color:#ffff55>msgnotify</color>
  
  <color:#55ffff>Description:</color> <color:#ffff55>This command allows you to change the notification sound</color>
  
  <color:#55ffff>Usage:</color> <color:#ffff55>/<command> <sound> <volume></color>
  
  
  <color:#55ffff>Command:</color> <color:#ffff55>addbl</color>
  
  <color:#55ffff>Description:</color> <color:#ffff55>This command allows you to add players to the blacklist</color>
  
  <color:#55ffff>Usage:</color> <color:#ffff55>/<command> <player></color>
  
  
  <color:#55ffff>Command:</color> <color:#ffff55>removebl</color>
  
  <color:#55ffff>Description:</color> <color:#ffff55>This command allows you to remove players from the blacklist</color>
  
  <color:#55ffff>Usage:</color> <color:#ffff55>/<command> <player></color>
  
  
  <color:#55ffff>Command:</color> <color:#ffff55>showbl</color>
  
  <color:#55ffff>Description:</color> <color:#ffff55>This command allows you to display your blacklist</color>
  
  <color:#55ffff>Usage:</color> <color:#ffff55>/<command></color>
  
  
  <color:#55ffff>Command:</color> <color:#ffff55>mail</color>
  
  <color:#55ffff>Description:</color> <color:#ffff55>This command allows you to view unread messages</color>
  
  <color:#55ffff>Usage:</color> <color:#ffff55>/<command></color>
  
  
  <color:#55ffff>Command:</color> <color:#ffff55>privatechatl</color>
  
  <color:#55ffff>Description:</color> <color:#ffff55>This command allows you to interact with private chats</color>
  
  <color:#55ffff>Usage:</color> <color:#ffff55>/<command> <action> <arg>(if required)</color>
  
  
  <color:#55ffff>Command:</color> <color:#ffff55>msgprop</color>
  
  <color:#55ffff>Description:</color> <color:#ffff55>This command allows you to set player properties</color>
  
  <color:#55ffff>Usage:</color> <color:#ffff55>/<command> <property> <arg></color>
  
  <b><color:#55ffff>⏴----------------------------⏵</color></b>'
