name: SimpleMsgPlugin
version: '${project.version}'
main: simplemsgplugin.SimpleMsgPlugin
api-version: '1.20'
authors: [ MouseJava ]
description: Plugin for messages in the game
commands:
  playermsg:
    description: This command allows you to send private messages to the player
    usage: /<command> <player> <message>
    aliases:
      - pm
      - msg
      - message
      - tell