name: SimpleMsgPlugin
version: '${project.version}'
main: simplemsgplugin.SimpleMsgPlugin
api-version: '1.20'
authors: [ MouseJava ]
description: Plugin for messages in the game
commands:
  msghelp:
    description: This command allows you to display all possible plugin commands
    permission: simplemsgplugin.msghelp
    usage: /<command>
    aliases:
      - msgh
  msgreloadconfig:
    description: This command allows you to reload the plugin config
    permission: simplemsgplugin.msgreloadconfig
    usage: /<command>
    aliases:
      - msgrc
      - reloadmsg
  playermsg:
    description: This command allows you to send private messages to the player
    permission: simplemsgplugin.playermsg
    usage: /<command> <player> <message>
    aliases:
      - pm
      - msg
      - message
      - tell
      - w
  replymsg:
    description: This command allows you to send a private message to the last player who wrote to you
    permission: simplemsgplugin.replymsg
    usage: /<command> <message>
    aliases:
      - reply
      - r
  acceptsend:
    description: This command allows you to accept sending an offline message
    permission: simplemsgplugin.acceptsend
    usage: /<command>
    aliases:
      - accsend
  msgnotification:
    description: This command allows you to change the notification sound
    permission: simplemsgplugin.msgnotification
    usage: /<command> <sound> <volume>
    aliases:
      - msgnotify
      - pmnotify
  addblacklist:
    description: This command allows you to add players to the blacklist
    permission: simplemsgplugin.addblacklist
    usage: /<command> <player>
    aliases:
      - addbl
      - ignore
  removeblacklist:
    description: This command allows you to remove players from the blacklist
    permission: simplemsgplugin.removeblacklist
    usage: /<command> <player>
    aliases:
      - removebl
      - unignore
  showblacklist:
    description: This command allows you to display your blacklist
    permission: simplemsgplugin.showblacklist
    usage: /<command>
    aliases:
      - showbl
  privatechat:
    description: This command allows you to interact with private chats
    permission: simplemsgplugin.privatechat
    usage: /<command> <action> <arg>(if required)
    aliases:
      - pvch
      - pc
  msgproperties:
    description: This command allows you to set player settings
    permission: simplemsgplugin.msgproperties
    usage: /<command> <property> <arg>
    aliases:
      - msgprop
  pmmail:
    description: This command allows you to view unread messages
    permission: simplemsgplugin.pmmail
    usage: /<command>
    aliases:
      - msgmail
      - mail
permissions:
  simplemsgplugin.msghelp:
    description: Permission to use command msghelp
    default: true
  simplemsgplugin.msgreloadconfig:
    description: Permission to use command msgrc
    default: op
  simplemsgplugin.playermsg:
    description: Permission to use command msg
    default: true
  simplemsgplugin.replymsg:
    description: Permission to use command reply
    default: true
  simplemsgplugin.acceptsend:
    description: Permission to use command acceptsend
    default: true
  simplemsgplugin.msgnotification:
    description: Permission to use command msgnotification
    default: true
  simplemsgplugin.addblacklist:
    description: Permission to use command addbl
    default: true
  simplemsgplugin.removeblacklist:
    description: Permission to use command removebl
    default: true
  simplemsgplugin.showblacklist:
    description: Permission to use command showbl
    default: true
  simplemsgplugin.privatechat:
    description: Permission to use command privatechat
    default: true
  simplemsgplugin.msgproperties:
    description: Permission to use command msgproperties
    default: true
  simplemsgplugin.pmmail:
    description: Permission to use command pmmail
    default: true
