name: SimpleMsgPlugin
version: '${project.version}'
main: simplemsgplugin.SimpleMsgPlugin
api-version: '1.20'
authors: [ MouseJava ]
description: Plugin for messages in the game
commands:
  msghelp:
    description: This command allows you to display all possible plugin commands
    usage: /<command>
    aliases:
      - msgh
  msgreloadconfig:
    description: This command allows you to reload the plugin config
    usage: /<command>
    aliases:
      - msgrc
  playermsg:
    description: This command allows you to send private messages to the player
    usage: /<command> <player> <message>
    aliases:
      - pm
      - msg
      - message
      - tell
  acceptsend:
    description: This command allows you to accept sending an offline message
    usage: /<command>
    aliases:
      - accsend
  changesound:
    description: This command allows you to change the notification sound
    usage: /<command> <sound>
    aliases:
      - cs
      - csound
  changevolume:
    description: This command allows you to change the notification volume
    usage: /<command> <volume>
    aliases:
      - cv
      - cvolume
  addblacklist:
    description: This command allows you to add players to the blacklist
    usage: /<command> <player>
    aliases:
      - addbl
  removeblacklist:
    description: This command allows you to remove players from the blacklist
    usage: /<command> <player>
    aliases:
      - removebl
  showblacklist:
    description: This command allows you to display your blacklist
    usage: /<command>
    aliases:
      - showbl